version: "3.8"
services:
  # DATABASE
  database:
    build:
      context: ./SDB_Database
      dockerfile: db.Dockerfile
    image: sdb_db:1.0.0
    container_name: sdb_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - /var/lib/mysql/sdb_db:/var/lib/mysql/
    ports:
      - "30306:3306"
    expose:
      - "30306"
    networks:
      - db_be
  # BACKEND
  backend:
    build:
      context: ./SDB_Backend
      dockerfile: be.Dockerfile
    # 'sdb_be' means 'SENAI Dashboard backend'
    image: sdb_be:1.0.0
    container_name: sdb_be
    restart: always
    command: node src/index.js
    volumes:
      - /usr/src/sdb_be:/usr/src/sdb_be
    ports:
      - "4000:4000"
    expose:
      - "4000"
    # List the containers that backend depends on
    depends_on:
      - database
    networks:
      - db_be
  # FRONTEND
  frontend:
    build:
      context: ./SDB_Frontend
      dockerfile: fe.Dockerfile
    # 'sdb_fe' means 'SENAI Dashboard frontend'
    image: sdb_fe:1.0.0
    container_name: sdb_fe
    restart: always
    volumes:
      - /var/www/html/:/var/www/html/
    ports:
      - "80:80"
    # List the containers that backend depends on
    depends_on:
      - database
      - backend
networks:
  # database <-> backend
  db_be: 
    driver: bridge


# TO DEPLOY:
# ON THIS DIRECTORY, RUN "docker compose up -d"



# References:
# BUILDING: https://docs.docker.com/compose/compose-file/build/
# DOCKER-COMPOSE SCOPE: https://www.youtube.com/watch?v=HxPz3eLnXZk
